import { Noto_Sans_JP, } from "next/font/google";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["japanese"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "うみのいきものずかん",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "いきものずかん",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable}  `}
      >
        <div className="w-full bg-yellow h-screen lg:py-10  ">
          <div className="w-full bg-blue h-full  lg:w-3xl m-auto lg:border-8 lg:border-black lg:rounded-3xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
